---
name: auto-comment
on: [issues, pull_request]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}, thank you for raising an issue!

            We will will investigate into the matter and get back to you as soon as possible. Please make sure you have
            given us as much context as possible.

          pullRequestOpened: |
            👋 @{{ author }}, thank you for your contribution!

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
